Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2204"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 1024
    vb.cpus = 1
  end

  config.vm.define "clyamaniS" do |server|
    server.vm.hostname = "clyamaniS"
    server.vm.network "private_network", ip: "192.168.56.110"

    server.vm.provider "virtualbox" do |vb|
      vb.name = "clyamaniS"
    end

    server.vm.provision "shell", path: "scripts/install_server.sh"
  end

  config.vm.define "clyamaniSW" do |worker|
    worker.vm.hostname = "clyamaniSW"
    worker.vm.network "private_network", ip: "192.168.56.111"

    worker.vm.provider "virtualbox" do |vb|
      vb.name = "clyamaniSW"
    end

    worker.vm.provision "shell", path: "scripts/install_worker.sh"
  end
end