Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2204"
  config.vm.boot_timeout = 600
  config.ssh.insert_key = false
  config.vm.synced_folder ".", "/vagrant"

  config.vm.define "clyamaniS" do |server|
    server.vm.hostname = "clyamaniS"
    server.vm.network "private_network", ip: "192.168.56.110"

    server.vm.provider "virtualbox" do |vb|
      vb.name = "clyamaniS"
      vb.memory = 1024
      vb.cpus = 1
    end

    server.vm.provision "shell", path: "scripts/install_server.sh"
    server.vm.provision "shell", path: "scripts/deploy_apps.sh" 
  end
end