CPU = 1 
MEMORY = 1024

Vagrant.configure("2") do |config|
  # Utilisation d'Ubuntu 22.04 LTS (dernière version stable très répandue)
  # config.vm.box = "generic/centos9s"
  config.vm.box = "bento/ubuntu-22.04"
  # ---------------------------------------------------------
  # PREMIÈRE MACHINE : Le Serveur (S)
  # ---------------------------------------------------------
  config.vm.define "clyamaniS" do |server|
    server.vm.hostname = "clyamaniS"
    server.vm.network "private_network", ip: "192.168.56.110"
        server.vm.network "forwarded_port", guest: 6443, host: 6443  # ????? 

    server.vm.provider "virtualbox" do |vb|
      vb.memory = MEMORY
      vb.cpus = CPU
      vb.name = "clyamaniS" 
    end

    # Appel du script externe pour le Master
    server.vm.provision "shell", path: "./scripts/install_server.sh"
  end

  # ---------------------------------------------------------
  # DEUXIÈME MACHINE : Le ServerWorker (SW)
  # ---------------------------------------------------------
  config.vm.define "clyamaniSW" do |worker|
    worker.vm.hostname = "clyamaniSW"
    worker.vm.network "private_network", ip: "192.168.56.111"

    worker.vm.provider "virtualbox" do |vb|
      vb.memory = MEMORY
      vb.cpus = CPU
      vb.name = "clyamaniSW" # Nom affiché dans l'interface VirtualBox
    end

    worker.vm.provision "shell", path: "./scripts/install_worker.sh"
  end

  # Configuration SSH globale (pour ne pas demander de mot de passe)
  config.ssh.insert_key = false
end